name: itemloretowny
version: '0.1.3'
description: OriginsTowny, was heavily inspired on EMC's lore plugin, much changes will be implemented soonTM.
main: com.orbismc.itemloretowny.TownyItemLore
api-version: '1.19'
depend: [ Towny , LuckPerms ]
author: InjurynSickness
